SELECT
?corrAns ?cDef ?d1 ?d2 ?d3 ?class
{
?class rdfs:label ?corrAns.
FILTER(LANGMATCHES(LANG(?corrAns),"en"))
# Subquery, da innerer Filter nicht funktional
# Sei ?corrAns die woertliche Umschreibung von ?class
{
SELECT
?class
SAMPLE(str(?AnswDefinition)) as ?cDef
SAMPLE(str(?dist1l)) as ?d1
SAMPLE(str(?dist2l)) as ?d2
SAMPLE(str(?dist3l)) as ?d3
# Select a SAMPLE (unique for every class) of answers to avoid repetition and similar questions
WHERE {
   # Sei ?class eine Klasse
 ?class a owl:Class.
   # Sei ?AnswDefinition die woertliche Definition von ?class
 ?class skos:definition ?AnswDefinition.
 # Filter for english definitions only.
 FILTER(LANGMATCHES(LANG(?AnswDefinition),"en"))

 # Seien ?dist1-2 Bestandteile von meta:chapter und im nahen Umfeld von ?class
 ?class (!(meta:subTopClass|meta:chapter)){1,2} ?dist1,?dist2,?dist3.
 # Seien ?dist1-3 Distraktoren
 owl:Class ^a ?dist1,?dist2,?dist3.
 # Filtern, um Aehnlichkeiten zwischen den Klassen zu verhindern
 FILTER(?class!=?dist1&&?class!=?dist2&&?class!=?dist3&&?dist1<?dist2&&?dist2<?dist3)

 # Woertliche Umschreibungen, pruefe englische Sprache
 ?dist1 rdfs:label ?dist1l.
 FILTER(LANGMATCHES(LANG(?dist1l),"en"))

 ?dist2 rdfs:label ?dist2l.
 FILTER(LANGMATCHES(LANG(?dist2l),"en"))

 ?dist3 rdfs:label ?dist3l.
 FILTER(LANGMATCHES(LANG(?dist3l),"en"))

 # Begrenze Laenge der Definition, um Lesbarkeit zu verbessern
 FILTER (STRLEN(?AnswDefinition)<225 && STRLEN(?AnswDefinition)>50).
   # Randomisiere Auswahl
 FILTER ( 1 >  <bif:rnd> (10, ?class) )
 FILTER (UCASE(SUBSTR(str(?AnswDefinition), 1, 1)))
}ORDER BY RAND() LIMIT 100
# Limitiere mit Anzahl der benoetigten Fragen
}
}GROUP BY ?class ORDER BY RAND()
